name: APT Repository

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache apt packages
      uses: actions/cache@v3
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          clang \
          make \
          libelf-dev \
          zlib1g-dev \
          pkg-config \
          build-essential \
          linux-headers-generic \
          libbpf-dev \
          debhelper \
          devscripts \
          dh-make \
          reprepro \
          gnupg2

    - name: Install bpftool
      run: |
        # Try to install bpftool from package manager first
        sudo apt-get install -y bpftool || {
          echo "bpftool not available in package manager, skipping..."
          echo "This is expected on some Ubuntu versions"
        }

    - name: Build application
      run: |
        make clean
        make

    - name: Update changelog with version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        VERSION=${VERSION#v}
        sed -i "s/1.0.0-1/$VERSION-1/" debian/changelog
        sed -i "s/$(date -R)/$(date -R)/" debian/changelog

    - name: Build Debian package
      run: |
        dpkg-buildpackage -b -us -uc
        ls -la ../*.deb

    - name: Copy Debian package to workspace
      run: |
        cp ../tty-egpf-monitor_*.deb .

    - name: Setup APT repository
      run: |
        # Create repository structure
        mkdir -p apt-repo/conf apt-repo/db apt-repo/dists apt-repo/pool
        
        # Create repository configuration
        cat > apt-repo/conf/distributions << EOF
        Origin: TTY EGPF Monitor
        Label: TTY EGPF Monitor Repository
        Codename: stable
        Architectures: amd64 arm64
        Components: main
        Description: TTY EGPF Monitor - Advanced Serial Port Monitoring with eBPF Technology
        EOF
        
        # Add package to repository
        reprepro -b apt-repo includedeb stable ../tty-egpf-monitor_*.deb
        
        # Create Release file
        cd apt-repo
        apt-ftparchive release . > Release

    - name: Upload Debian package artifact
      uses: actions/upload-artifact@v4
      with:
        name: tty-egpf-monitor-deb
        path: tty-egpf-monitor_*.deb
        retention-days: 30

    - name: Setup Pages
      uses: actions/configure-pages@v4
      with:
        enablement: true

    - name: Upload to Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: apt-repo/

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
