name: Build Package

on:
  workflow_dispatch:

jobs:
  build-package:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache apt packages
      uses: actions/cache@v3
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          clang \
          make \
          libelf-dev \
          zlib1g-dev \
          pkg-config \
          build-essential \
          linux-headers-generic \
          libbpf-dev \
          debhelper \
          devscripts \
          dh-make

    - name: Install bpftool
      run: |
        # Try to install bpftool from package manager first
        sudo apt-get install -y bpftool || {
          echo "bpftool not available in package manager, skipping..."
          echo "This is expected on some Ubuntu versions"
        }

    - name: Build application
      run: |
        make clean
        make

    - name: Build Debian package
      run: |
        dpkg-buildpackage -b -us -uc
        ls -la ../*.deb

    - name: Copy Debian package to workspace
      run: |
        cp ../tty-egpf-monitor_*.deb .

    - name: Upload Debian package artifact
      uses: actions/upload-artifact@v4
      with:
        name: tty-egpf-monitor-deb
        path: tty-egpf-monitor_*.deb
        retention-days: 30
