name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Apt cache
        uses: actions/cache@v3
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('**/debian/control') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang make libelf-dev zlib1g-dev pkg-config build-essential libbpf-dev \
            linux-tools-common linux-tools-generic

      - name: Ensure bpftool
        run: |
          set -e
          if ! command -v bpftool >/dev/null 2>&1; then
            BPFDIR=$(ls -d /usr/lib/linux-tools-* 2>/dev/null | head -n1 || true)
            if [ -n "$BPFDIR" ] && [ -x "$BPFDIR/bpftool" ]; then
              sudo ln -sf "$BPFDIR/bpftool" /usr/local/bin/bpftool
            fi
          fi
          bpftool version || true

      - name: Build
        run: |
          make clean
          make

      - name: Check binaries
        run: |
          ls -la build/
          file build/tty-egpf-monitord
          file build/tty-egpf-monitor
          test -x build/tty-egpf-monitord
          test -x build/tty-egpf-monitor

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            build/tty-egpf-monitord
            build/tty-egpf-monitor
            build/sniffer.bpf.o


