name: Build Package

on:
  workflow_dispatch:

jobs:
  build-package:
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache apt packages
      uses: actions/cache@v3
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          clang \
          make \
          libelf-dev \
          zlib1g-dev \
          pkg-config \
          build-essential \
          linux-headers-generic \
          libbpf-dev \
          debhelper \
          devscripts \
          dh-make

    - name: Ensure bpftool
      run: |
        set -e
        if ! command -v bpftool >/dev/null 2>&1; then
          sudo apt-get install -y linux-tools-common linux-tools-generic
          BPFDIR=$(ls -d /usr/lib/linux-tools-* 2>/dev/null | head -n1 || true)
          if [ -n "$BPFDIR" ] && [ -x "$BPFDIR/bpftool" ]; then
            sudo ln -sf "$BPFDIR/bpftool" /usr/local/bin/bpftool
          fi
        fi
        bpftool version || true

    - name: Build application
      run: |
        make clean
        make

    - name: Clean Debian outputs
      run: |
        sudo rm -f ../*.deb ../*.buildinfo ../*.changes || true
        sudo rm -rf debian/tty-egpf-monitor debian/tty-egpf-monitord debian/tty-egpf-monitor-cli || true

    - name: Build Debian package
      run: |
        dpkg-buildpackage -b -us -uc
        ls -la ../*.deb

    - name: Copy Debian packages to workspace
      run: |
        cp ../*.deb .

    - name: Upload Debian package artifact
      uses: actions/upload-artifact@v4
      with:
        name: debs
        path: '*.deb'
        retention-days: 30
