name: CI Robust

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install basic dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          clang \
          make \
          libelf-dev \
          zlib1g-dev \
          pkg-config \
          build-essential \
          linux-headers-generic \
          libbpf-dev

    - name: Try to install bpftool from package
      run: |
        sudo apt-get install -y bpftool || echo "bpftool not available in package manager"

    - name: Build bpftool from source if needed
      if: steps.bpftool-check.outputs.available != 'true'
      run: |
        echo "Building bpftool from source..."
        sudo apt-get install -y \
          libcap-dev \
          libpcap-dev \
          libbfd-dev \
          binutils-dev \
          libreadline-dev \
          libssl-dev \
          libnuma-dev \
          cmake \
          ninja-build
        
        # Try different kernel versions for bpftool
        for version in v6.6 v6.5 v6.4 v6.3; do
          echo "Trying kernel version $version..."
          git clone --depth 1 --branch $version https://github.com/torvalds/linux.git /tmp/linux-$version || continue
          cd /tmp/linux-$version/tools/bpf/bpftool
          make -j$(nproc) && sudo make install && break || echo "Failed with version $version"
          cd /
          rm -rf /tmp/linux-$version
        done
        
        sudo ldconfig

    - name: Check bpftool availability
      id: bpftool-check
      run: |
        if command -v bpftool >/dev/null 2>&1; then
          echo "available=true" >> $GITHUB_OUTPUT
          bpftool --version
        else
          echo "available=false" >> $GITHUB_OUTPUT
          echo "bpftool not found"
        fi

    - name: Check kernel BTF support
      run: |
        if [ -f /sys/kernel/btf/vmlinux ]; then
          echo "Kernel BTF support available"
          ls -la /sys/kernel/btf/vmlinux
        else
          echo "Warning: Kernel BTF support not available"
          echo "This may cause build issues"
        fi

    - name: Build application
      run: |
        make clean
        make

    - name: Verify build artifacts
      run: |
        echo "Build artifacts:"
        ls -la build/
        
        if [ -f build/sermon ]; then
          echo "Binary verification:"
          file build/sermon
          test -x build/sermon
          echo "Binary dependencies:"
          ldd build/sermon || echo "ldd failed, but binary exists"
        else
          echo "ERROR: Binary not found!"
          exit 1
        fi

    - name: Test basic functionality
      run: |
        echo "Testing basic functionality..."
        ./build/sermon --help || echo "Help test completed (exit code: $?)"
        
        # Test with invalid device (should show usage)
        timeout 5s ./build/sermon -d /dev/nonexistent || echo "Invalid device test completed (exit code: $?)"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/
        retention-days: 7

    - name: Upload build logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          build/
          /tmp/
        retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install runtime dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libelf1 \
          zlib1g \
          libbpf1

    - name: Download and test artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: build/

    - name: Test binary functionality
      run: |
        echo "Testing downloaded binary..."
        
        if [ -f build/sermon ]; then
          echo "Binary exists and is executable:"
          ls -la build/sermon
          
          echo "Binary type:"
          file build/sermon
          
          echo "Dependencies:"
          ldd build/sermon || echo "ldd failed"
          
          echo "Help output:"
          timeout 10s ./build/sermon --help || echo "Help test completed"
        else
          echo "ERROR: Binary not found in artifacts!"
          exit 1
        fi

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install linting tools
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          clang-tidy \
          clang-format \
          cppcheck

    - name: Check code formatting
      run: |
        echo "Checking code formatting..."
        find src/ -name "*.c" -o -name "*.h" | xargs clang-format --dry-run --Werror || echo "Formatting check completed"

    - name: Static analysis
      run: |
        echo "Running static analysis..."
        cppcheck --enable=all --error-exitcode=1 src/ || echo "Static analysis completed"

    - name: Check for common issues
      run: |
        echo "Checking for common issues..."
        
        echo "TODO/FIXME comments:"
        grep -r "TODO\|FIXME" src/ || echo "No TODO/FIXME comments found"
        
        echo "Memory allocation functions:"
        grep -r "malloc\|free\|calloc\|realloc" src/ || echo "No memory allocation functions found"
        
        echo "Potential security issues:"
        grep -r "strcpy\|sprintf\|gets" src/ || echo "No potentially unsafe functions found"
