name: CI Simple

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          clang \
          make \
          libelf-dev \
          zlib1g-dev \
          pkg-config \
          build-essential \
          linux-headers-generic \
          libbpf-dev \
          bpftool

    - name: Verify bpftool
      run: |
        bpftool --version
        which bpftool

    - name: Build application
      run: |
        make clean
        make

    - name: Verify build
      run: |
        ls -la build/
        file build/sermon
        test -x build/sermon
        ./build/sermon --help || echo "Help test completed"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/
        retention-days: 7

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install minimal dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libelf1 \
          zlib1g \
          libbpf1

    - name: Download and test artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: build/

    - name: Test binary
      run: |
        ldd build/sermon
        ./build/sermon --help || echo "Binary test completed"
