name: CI Simple

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          clang \
          make \
          libelf-dev \
          zlib1g-dev \
          pkg-config \
          build-essential \
          linux-headers-generic \
          libbpf-dev
        
        # Try to install bpftool from package, build from source if needed
        sudo apt-get install -y bpftool || {
          echo "bpftool not available in package manager, building from source..."
          sudo apt-get install -y \
            libcap-dev \
            libpcap-dev \
            libbfd-dev \
            binutils-dev \
            libreadline-dev \
            libssl-dev \
            libnuma-dev \
            cmake \
            ninja-build \
            llvm
          
          git clone --depth 1 --branch v6.6 https://github.com/torvalds/linux.git /tmp/linux
          cd /tmp/linux/tools/bpf/bpftool
          make -j$(nproc)
          sudo make install
          sudo ldconfig
        }

    - name: Verify bpftool
      run: |
        bpftool --version
        which bpftool

    - name: Build application
      run: |
        make clean
        make

    - name: Verify build
      run: |
        ls -la build/
        file build/sermon
        test -x build/sermon
        echo "Binary size: $(stat -c%s build/sermon) bytes"
        echo "Binary verification completed (not executing eBPF programs on runner)"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/
        retention-days: 7


