name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache apt packages
      uses: actions/cache@v3
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          clang \
          make \
          libelf-dev \
          zlib1g-dev \
          pkg-config \
          build-essential \
          libbpf-dev \
          linux-tools-common linux-tools-generic

    - name: Ensure bpftool
      run: |
        set -e
        if ! command -v bpftool >/dev/null 2>&1; then
          BPFDIR=$(ls -d /usr/lib/linux-tools-* 2>/dev/null | head -n1 || true)
          if [ -n "$BPFDIR" ] && [ -x "$BPFDIR/bpftool" ]; then
            sudo ln -sf "$BPFDIR/bpftool" /usr/local/bin/bpftool
          fi
        fi
        bpftool version || true

    - name: Build application
      run: |
        make clean
        make

    - name: Verify build artifacts
      run: |
        ls -la build/
        file build/tty-egpf-monitord
        file build/tty-egpf-monitor
        # Check if the binaries are executable
        test -x build/tty-egpf-monitord
        test -x build/tty-egpf-monitor

    - name: Test basic functionality
      run: |
        # Verify binary properties (not executing eBPF programs on runner)
        echo "Binary verification:"
        file build/tty-egpf-monitord
        file build/tty-egpf-monitor
        echo "Monitord size: $(stat -c%s build/tty-egpf-monitord) bytes"
        echo "CLI size: $(stat -c%s build/tty-egpf-monitor) bytes"
        echo "Monitord perms: $(stat -c%a build/tty-egpf-monitord)"
        echo "CLI perms: $(stat -c%a build/tty-egpf-monitor)"
        
        # Test that required libraries are linked
        ldd build/tty-egpf-monitord
        ldd build/tty-egpf-monitor

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tty-egpf-build
        path: |
          build/tty-egpf-monitord
          build/tty-egpf-monitor
          build/sniffer.bpf.o
        retention-days: 7


