name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache apt packages
      uses: actions/cache@v3
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          clang \
          make \
          libelf-dev \
          zlib1g-dev \
          pkg-config \
          build-essential \
          linux-headers-$(uname -r) \
          libbpf-dev \
          bpftool

    - name: Verify bpftool installation
      run: |
        bpftool --version
        which bpftool

    - name: Build application
      run: |
        make clean
        make

    - name: Verify build artifacts
      run: |
        ls -la build/
        file build/sermon
        # Check if the binary is executable
        test -x build/sermon

    - name: Test basic functionality
      run: |
        # Verify binary properties (not executing eBPF programs on runner)
        echo "Binary verification:"
        file build/sermon
        echo "Binary size: $(stat -c%s build/sermon) bytes"
        echo "Binary permissions: $(stat -c%a build/sermon)"
        
        # Test that required libraries are linked
        ldd build/sermon

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tty-egpf-monitor-build
        path: build/sermon
        retention-days: 7


