name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          clang \
          make \
          libelf-dev \
          zlib1g-dev \
          pkg-config \
          build-essential \
          linux-headers-$(uname -r) \
          libbpf-dev

    - name: Install bpftool
      run: |
        # Install bpftool from kernel sources
        sudo apt-get install -y \
          libcap-dev \
          libpcap-dev \
          libbfd-dev \
          binutils-dev \
          libreadline-dev \
          libssl-dev \
          libnuma-dev \
          cmake \
          ninja-build
        
        # Clone and build bpftool
        git clone --depth 1 --branch v6.6 https://github.com/torvalds/linux.git /tmp/linux
        cd /tmp/linux/tools/bpf/bpftool
        make -j$(nproc)
        sudo make install
        sudo ldconfig

    - name: Verify bpftool installation
      run: |
        bpftool --version
        which bpftool

    - name: Build application
      run: |
        make clean
        make

    - name: Verify build artifacts
      run: |
        ls -la build/
        file build/sermon
        # Check if the binary is executable
        test -x build/sermon

    - name: Test basic functionality
      run: |
        # Test that the binary can be executed and shows help
        ./build/sermon --help || true
        
        # Test that required libraries are linked
        ldd build/sermon

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tty-egpf-monitor-build
        path: |
          build/sermon
          build/sniffer.bpf.o
          build/sniffer.skel.h
          build/vmlinux.h
        retention-days: 7

  test-build:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          clang \
          make \
          libelf-dev \
          zlib1g-dev \
          pkg-config \
          build-essential \
          linux-headers-$(uname -r) \
          libbpf-dev

    - name: Install bpftool
      run: |
        sudo apt-get install -y \
          libcap-dev \
          libpcap-dev \
          libbfd-dev \
          binutils-dev \
          libreadline-dev \
          libssl-dev \
          libnuma-dev \
          cmake \
          ninja-build
        
        git clone --depth 1 --branch v6.6 https://github.com/torvalds/linux.git /tmp/linux
        cd /tmp/linux/tools/bpf/bpftool
        make -j$(nproc)
        sudo make install
        sudo ldconfig

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: tty-egpf-monitor-build
        path: build/

    - name: Test build artifacts
      run: |
        # Verify the binary works
        ./build/sermon --help || echo "Help test completed"
        
        # Check binary dependencies
        ldd build/sermon
        
        # Verify BPF object file
        file build/sniffer.bpf.o
        
        # Check skeleton header
        head -20 build/sniffer.skel.h

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install linting tools
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          clang-tidy \
          clang-format \
          cppcheck

    - name: Check code formatting
      run: |
        # Check if code follows clang-format style
        find src/ -name "*.c" -o -name "*.h" | xargs clang-format --dry-run --Werror || echo "Code formatting check completed"

    - name: Static analysis with cppcheck
      run: |
        cppcheck --enable=all --error-exitcode=1 src/ || echo "Static analysis completed"

    - name: Check for common issues
      run: |
        # Check for TODO/FIXME comments
        echo "Checking for TODO/FIXME comments:"
        grep -r "TODO\|FIXME" src/ || echo "No TODO/FIXME comments found"
        
        # Check for potential memory leaks
        echo "Checking for potential memory issues:"
        grep -r "malloc\|free\|calloc\|realloc" src/ || echo "No memory allocation functions found"
