name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        codename: [ noble, jammy ]
        include:
          - codename: noble
            container: ubuntu:24.04
          - codename: jammy
            container: ubuntu:22.04
    container: ${{ matrix.container }}
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache apt packages
      uses: actions/cache@v3
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Install build dependencies
      run: |
        apt-get update
        apt-get install -y \
          clang \
          make \
          libelf-dev \
          zlib1g-dev \
          pkg-config \
          build-essential \
          linux-headers-generic \
          libbpf-dev \
          bpftool \
          gnupg \
          apt-utils \
          dpkg-dev \
          debhelper \
          devscripts \
          dh-make

    - name: Ensure bpftool
      run: |
        set -e
        if ! command -v bpftool >/dev/null 2>&1; then
          apt-get install -y linux-tools-common linux-tools-generic || true
          BPFDIR=$(ls -d /usr/lib/linux-tools-* 2>/dev/null | head -n1 || true)
          if [ -n "$BPFDIR" ] && [ -x "$BPFDIR/bpftool" ]; then
            ln -sf "$BPFDIR/bpftool" /usr/local/bin/bpftool
          fi
        fi
        bpftool version || true

    - name: Build application
      run: |
        make clean
        make

    - name: Update changelog with version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        VERSION=${VERSION#v}
        sed -i "s/1.0.0-1/$VERSION-1/" debian/changelog
        sed -i "s/$(date -R)/$(date -R)/" debian/changelog

    - name: Clean Debian outputs
      run: |
        rm -f ../*.deb ../*.buildinfo ../*.changes || true
        rm -rf debian/tty-egpf-monitor debian/tty-egpf-monitord debian/tty-egpf-monitor-cli || true

    - name: Build Debian package
      run: |
        dpkg-buildpackage -b -us -uc
        ls -la ../*.deb

    - name: Copy Debian packages to workspace
      run: |
        cp ../*.deb .

    - name: Upload Debian package artifact
      uses: actions/upload-artifact@v4
      with:
        name: debs
        path: '*.deb'
        retention-days: 30

    - name: Publish apt repo to gh-pages
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        REPO: ${{ github.repository }}
      run: |
        set -e
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        rm -rf /tmp/apt-repo
        git clone --depth 1 --branch gh-pages "https://x-access-token:${GH_TOKEN}@github.com/${REPO}.git" /tmp/apt-repo || {
          mkdir -p /tmp/apt-repo
          cd /tmp/apt-repo
          git init
          git checkout -b gh-pages
          git remote add origin "https://x-access-token:${GH_TOKEN}@github.com/${REPO}.git"
          cd -
        }
        CODENAME='${{ matrix.codename }}'
        mkdir -p /tmp/apt-repo/pool/main
        mkdir -p /tmp/apt-repo/dists/${CODENAME}/main/binary-amd64
        cp ./*.deb /tmp/apt-repo/pool/main/
        cd /tmp/apt-repo
        apt-ftparchive packages pool/main > dists/${CODENAME}/main/binary-amd64/Packages
        gzip -c dists/${CODENAME}/main/binary-amd64/Packages > dists/${CODENAME}/main/binary-amd64/Packages.gz
        apt-ftparchive \
          -o APT::FTPArchive::Release::Label="tty-egpf-monitor" \
          -o APT::FTPArchive::Release::Suite="${CODENAME}" \
          -o APT::FTPArchive::Release::Codename="${CODENAME}" \
          -o APT::FTPArchive::Release::Architectures="amd64" \
          -o APT::FTPArchive::Release::Components="main" \
          release dists/${CODENAME} > dists/${CODENAME}/Release
        touch .nojekyll
        # Publish public key at root for clients (both .asc and .gpg)
        KEYASC=""
        if [ -f "$GITHUB_WORKSPACE/public-apt-key.asc" ]; then
          cp "$GITHUB_WORKSPACE/public-apt-key.asc" ./public-apt-key.asc
          KEYASC="public-apt-key.asc"
        else
          CAND=$(ls "$GITHUB_WORKSPACE"/*.asc 2>/dev/null | head -n1 || true)
          if [ -n "$CAND" ]; then
            cp "$CAND" ./public-apt-key.asc
            KEYASC="public-apt-key.asc"
          elif [ -n "$GPG_PRIVATE_KEY" ]; then
            echo "$GPG_PRIVATE_KEY" | gpg --batch --yes --import
            gpg --armor --export > ./public-apt-key.asc || true
            KEYASC="public-apt-key.asc"
          fi
        fi
        if [ -n "$KEYASC" ]; then
          gpg --dearmor < "$KEYASC" > ./public-apt-key.gpg || true
        fi
        if [ -n "$GPG_PRIVATE_KEY" ]; then
          echo "$GPG_PRIVATE_KEY" | gpg --batch --yes --import
          gpg --batch --yes --pinentry-mode loopback --passphrase "$GPG_PASSPHRASE" -abs -o dists/${CODENAME}/Release.gpg dists/${CODENAME}/Release
          gpg --batch --yes --pinentry-mode loopback --passphrase "$GPG_PASSPHRASE" --clearsign -o dists/${CODENAME}/InRelease dists/${CODENAME}/Release || true
        fi
        git add -A
        git commit -m "Update apt repo for ${GITHUB_REF} (${CODENAME})" || git commit -m "Initialize apt repo"
        git push -u origin gh-pages
        cd -
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: '*.deb'
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
